// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9AfbyyuvwWIfK0XL0Ax64fzaXAiGIBI',
    appId: '1:1043365558412:web:7cd60deaf169e98ccae3a9',
    messagingSenderId: '1043365558412',
    projectId: 'topd-apps-91b2d',
    authDomain: 'topd-apps-91b2d.firebaseapp.com',
    storageBucket: 'topd-apps-91b2d.appspot.com',   // FIXED
    measurementId: 'G-6CZ9VSHSTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ozOiUDnuXpEgGTZm9x0gGhxNMh7FPiY',
    appId: '1:1043365558412:android:9fea96e89bc130f9cae3a9',
    messagingSenderId: '1043365558412',
    projectId: 'topd-apps-91b2d',
    storageBucket: 'topd-apps-91b2d.appspot.com',   // FIXED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtAs8GdGYrEAeFxxw2r1AZoAaBUjq4uFE',
    appId: '1:1043365558412:ios:33df61cd6a999618cae3a9',
    messagingSenderId: '1043365558412',
    projectId: 'topd-apps-91b2d',
    storageBucket: 'topd-apps-91b2d.appspot.com',   // FIXED
    iosBundleId: 'com.example.topdApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd9AfbyyuvwWIfK0XL0Ax64fzaXAiGIBI',
    appId: '1:1043365558412:web:08765a0e0dfda42ccae3a9',
    messagingSenderId: '1043365558412',
    projectId: 'topd-apps-91b2d',
    authDomain: 'topd-apps-91b2d.firebaseapp.com',
    storageBucket: 'topd-apps-91b2d.appspot.com',   // FIXED
    measurementId: 'G-6Y0FL1YMT4',
  );
}
