import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

// --- Services ---
import 'package:topd_apps/auth/auth_service.dart';
import 'package:topd_apps/services/cart_service.dart';
import 'package:topd_apps/services/firestore_service.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

// --- Auth Screens ---
import 'package:topd_apps/screens/auth/login_screen.dart';
import 'package:topd_apps/screens/auth/signup_screen.dart';
import 'package:topd_apps/screens/auth/forgate_password.dart';

// --- Admin Screens ---
import 'package:topd_apps/screens/admin/admin_dashboard.dart';
import 'package:topd_apps/screens/admin/admin_categories_screen.dart';
import 'package:topd_apps/screens/admin/add_category_screen.dart';
import 'package:topd_apps/screens/admin/admin_menu_items.dart';
import 'package:topd_apps/screens/admin/add_menu_item.dart'; // Ensure this contains AddEditMenuItemScreen
import 'package:topd_apps/screens/admin/admin_orders_screen.dart';
import 'package:topd_apps/screens/admin/admin_users_screen.dart';

// --- User/Main Screens ---
import 'package:topd_apps/screens/main/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  if (Firebase.apps.isEmpty) {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  }

  runApp(
    MultiProvider(
      providers: [
        // Auth Provider
        ChangeNotifierProvider(create: (_) => AuthService()),

        // Cart Provider (Required for "Add" button in ProductListScreen)
        ChangeNotifierProvider(create: (_) => CartService()),

        // Firestore Service (If used separately)
        Provider(create: (_) => FirestoreService()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Taste of Purani Dilli', // Fixed typo "Teste" -> "Taste"
      debugShowCheckedModeBanner: false,

      // --- App Theme ---
      theme: ThemeData(
        colorSchemeSeed: Colors.deepOrange,
        useMaterial3: true,
        scaffoldBackgroundColor: Colors.grey[50],

        appBarTheme: AppBarTheme(
          backgroundColor: Colors.deepOrange.shade700,
          foregroundColor: Colors.white,
          centerTitle: true,
          elevation: 0,
        ),

        floatingActionButtonTheme: FloatingActionButtonThemeData(
          backgroundColor: Colors.deepOrange.shade700,
          foregroundColor: Colors.white,
        ),

        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.deepOrange.shade700,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 15),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),

        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.white,
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: BorderSide(color: Colors.deepOrange.shade200),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: BorderSide(color: Colors.grey.shade300),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: BorderSide(color: Colors.deepOrange.shade700, width: 2),
          ),
          labelStyle: TextStyle(color: Colors.deepOrange.shade700),
        ),
      ),

      // --- Navigation Routes ---
      initialRoute: '/',
      routes: {
        '/': (context) => const AuthWrapper(),

        // Auth Routes
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignUpScreen(),
        '/forgotPassword': (context) => ForgotPasswordPage(),

        // User Routes
        '/home': (context) => const HomeScreen(),
        // Note: ProductListScreen doesn't need a named route here
        // because we push it dynamically with arguments (CategoryId)

        // Admin Routes
        '/admin': (context) => const AdminDashboard(),
        '/admin/categories': (context) => const AdminCategoriesScreen(),
        '/admin/addCategory': (context) => const AddCategoryScreen(),
        '/admin/menuItems': (context) => const AdminMenuItemsScreen(),

        // This points to the updated screen we created earlier
        '/admin/addMenuItem': (context) => const AddEditMenuItemScreen(),

        '/admin/orders': (context) => const AdminOrdersScreen(),
        '/admin/users': (context) => const AdminUsersScreen(),
      },
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    final authService = Provider.of<AuthService>(context);

    return StreamBuilder<User?>(
      stream: authService.user,
      builder: (context, snapshot) {
        // Wait for connection
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }

        if (snapshot.hasData) {
          final user = snapshot.data!;

          // Check for Admin Custom Claims
          return FutureBuilder<IdTokenResult>(
            future: user.getIdTokenResult(), // Removed 'true' to prevent infinite loop on rebuilds
            builder: (context, tokenSnapshot) {
              if (tokenSnapshot.connectionState == ConnectionState.waiting) {
                return const Scaffold(body: Center(child: CircularProgressIndicator()));
              }

              final claims = tokenSnapshot.data?.claims;
              final isAdmin = claims?['admin'] == true;

              if (isAdmin) {
                return const AdminDashboard();
              } else {
                return const HomeScreen();
              }
            },
          );
        } else {
          // No user logged in
          return const LoginScreen();
        }
      },
    );
  }
}